/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Program;

import Control.Servants;
import MOdel.ProgramParameter;
import View.TreeFolder;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Administrator
 */
public class ShowConfig extends javax.swing.JPanel {

    private final boolean isInput;
    private final boolean isDefaultFolder;
    private final VersionChange versionChange;
    private final String name;
    private final String project;
    private final TreeFolder treeFolder;

    /**
     * Creates new form ShowConfig
     *
     * @param project
     * @param name
     * @param isDefaultFolder
     * @param isInput
     */
    public ShowConfig(String project, String name, boolean isDefaultFolder, boolean isInput) {
        this.project = project;
        this.isInput = isInput;
        this.isDefaultFolder = isDefaultFolder;
        this.name = name;
        this.treeFolder = new TreeFolder();
        this.treeFolder.removeAll();
        initComponents();
        this.versionChange = new VersionChange(txtF_major, txtF_minor, txtF_patcher, txtF_revision, isInput);
        if (isDefaultFolder) {
            this.setBackground(Color.GREEN);
        }
    }

    @Override
    public String getName() {
        return name;
    }

    public void setFilePath(File folder) {
        if (!folder.exists()) {
            return;
        }
        this.treeFolder.setRoot(folder);
    }

    public ProgramParameter getConfigParamet() throws Exception {
        return new ProgramParameter().setProjectName(project)
                .setConfigName(name).setVersion(this.versionChange.getVersion())
                .setDescription( txtDetail.getText(), name).setFolderType(isDefaultFolder ? 0 : 1)
                .setFolderSource(txtFilePath.getText()).setLists(this.treeFolder.getAllFile());
    }

    private void chosseFilePath() throws HeadlessException {
        JFileChooser fc = this.treeFolder.chosseFileRoot();
        if (fc == null) {
            return;
        }
        this.txtFilePath.setText(fc.getSelectedFile().getPath());
        this.treeFolder.setRoot(fc.getSelectedFile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtF_major = new javax.swing.JFormattedTextField();
        txtF_minor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtF_patcher = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtF_revision = new javax.swing.JFormattedTextField();
        txtFilePath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        pnTree = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Version");

        txtF_major.setEditable(false);
        txtF_major.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_major.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtF_major.setMinimumSize(new java.awt.Dimension(40, 22));
        txtF_major.setPreferredSize(new java.awt.Dimension(40, 22));

        txtF_minor.setEditable(false);
        txtF_minor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_minor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtF_minor.setMinimumSize(new java.awt.Dimension(40, 22));
        txtF_minor.setPreferredSize(new java.awt.Dimension(40, 22));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(".");

        txtF_patcher.setEditable(false);
        txtF_patcher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_patcher.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtF_patcher.setMinimumSize(new java.awt.Dimension(40, 22));
        txtF_patcher.setPreferredSize(new java.awt.Dimension(40, 22));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(".");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".");

        txtF_revision.setEditable(false);
        txtF_revision.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_revision.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtF_revision.setMinimumSize(new java.awt.Dimension(40, 22));
        txtF_revision.setPreferredSize(new java.awt.Dimension(40, 22));

        txtFilePath.setEditable(false);
        txtFilePath.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFilePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFilePathMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Path");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("description");

        txtDetail.setColumns(10);
        txtDetail.setLineWrap(true);
        txtDetail.setRows(3);
        txtDetail.setTabSize(5);
        txtDetail.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDetail);

        pnTree.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnTree.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Folder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFilePath)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtF_major, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtF_minor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtF_patcher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtF_revision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(txtF_minor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtF_patcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtF_revision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtF_major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(pnTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        if(isInput){
            txtF_major.setText("1");
        }
        if(isInput){
            txtF_minor.setText("0");
        }
        if(isInput){
            txtF_patcher.setText("0");
        }
        if(isInput){
            txtF_revision.setText("0");
        }
        pnTree.add(this.treeFolder);
    }// </editor-fold>//GEN-END:initComponents


    private void txtFilePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilePathMouseClicked
        if (evt.getClickCount() < 2 || !isInput) {
            return;
        }
        chosseFilePath();
    }//GEN-LAST:event_txtFilePathMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnTree;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JFormattedTextField txtF_major;
    private javax.swing.JFormattedTextField txtF_minor;
    private javax.swing.JFormattedTextField txtF_patcher;
    private javax.swing.JFormattedTextField txtF_revision;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables

}
